server:
       port: 8082
       host: localhost

hibernate.format_sql: true

spring:
      datasource:
                 url: jdbc:mysql://localhost:3306/be?createDatabaseIfNotExist=true
                 username: root
                 password: root
                 platform: sql
                 initialization-mode: always
      jpa:
           hibernate:
                     ddl-auto: update
                     mapping-strategy: org.hibernate.cfg.ImprovedNamingStrategy
           properties:
                      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
           show-sql: true

logging:
       level:
             org.springframework: DEBUG
             com.howtodoinjava: DEBUG



dm:
  np: ADBMST,ALGYRMST,ANZBGL,AUCWW,AUDVMST,AUSDHMST,AUSGRID,AUTARGET,AUTOLL,CLPMST,COKE,CCAMTMST,ENECOMST,HCFAUMST,HKJCMST,ICAREMST,LIFULMST,M1LTD,MECCAMST,MENESMST,NAB,NBNCOMST,NSWDEMST,OPTUS,PENTSOLU,PERMTMST,POLHKMST,POLO,RACQMST,SDGOEMST,SYSCO,SHBTCMST,SINGTMST,SRSTLMST,TELNZMST,TELSTMST,TMKHDMST,TOMCOMST,TOSHAPAC,TRADUMST,UNIBKMST,WESTPAC
  amit: Amit1, Amit2, Amit3
  harish: Harish1, Harish2, Harish3
  bindu: Bindu1, Bindu2, Bindu3
  #all: ADBMST,ALGYRMST,ANZBGL,AUCWW,AUDVMST,AUSDHMST,AUSGRID,AUTARGET,AUTOLL,CLPMST,COKE,CCAMTMST,ENECOMST,HCFAUMST,HKJCMST,ICAREMST,LIFULMST,M1LTD,MECCAMST,MENESMST,NAB,NBNCOMST,NSWDEMST,OPTUS,PENTSOLU,PERMTMST,POLHKMST,POLO,RACQMST,SDGOEMST,SYSCO,SHBTCMST,SINGTMST,SRSTLMST,TELNZMST,TELSTMST,TMKHDMST,TOMCOMST,TOSHAPAC,TRADUMST,UNIBKMST,WESTPAC
  all: ADBMST, ALGYRMST, ANZBGL, AUCWW, AUDVMST, AUSDHMST, AUSGRID, AUTOLL, COKE, CCAMTMST, ENECOMST, HCFAUMST, ICAREMST, LIFULMST, M1LTD, MECCAMST, MENESMST, NAB, NBNCOMST, NSWDEMST, OPTUS, PENTSOLU, PERMTMST, POLHKMST, POLO, RACQMST, SDGOEMST, SHBTCMST, SGHSLMST, SINGTMST, SRSTLMST, TELNZMST, TELSTMST, TMKHDMST, TOMCOMST, TOSHAPAC, TRADUMST, WESTPAC,ADECCOGR, LGSPMKN, SABRE, SABRECO, UPCBBMST, SCHLMAST, AMDUSMST, AMEREN, APSMAST, AVNETMST, BEDBATH, BELGMAST, BH1, BHPBNMST, BPMAST, BTMAST, CAUASMST, CHCMST, CISCOMST, CONDTMST, CONEDMST, COPARMST, CYPREMST, EONMST, ESSENT, BAINCMST, EXELOMST, EXXNMMST, F5NETMST, FPLMAST, HPECOMST, HPQMST, INGRDMST, INMARMST, INOGYMST, INTELMST, LEVEL3, MarveMST, NALCHMST, NOKINMST, NUOOOOO1, NWNATMST, PGEMST, POYRYMST, PWC, SBCMST, SCEDISON, SFDCMSTT, SSEPLC, SSESLMST, STHCOMST, TECLMST, TMBUSMST, TRULPMST, UCASMST, UK-MOB-1, UNIPERGDE, UNPERGDE, VERIZMST, VFLNZMST, WELSHMST,ABBMST, ADIDMAST, NRPCMST, AGCINTMA, APPLE, AVON, BASFITG, BNSF, BOEINMST, bpostMST, BSHTGMST, CAMPBMST, CAT, MSCOKMST, CONAGMST, CUMMINS, DHLMST, DTCHLMST, EDGEMST, EMRSMAST, ENERMST, FEDMEMST, GAPMAST, GEFCOMST, HERSHMST, HYUNDAI, ICABMST, INBEV, JCMASTER, JPGMST, JPGMST, KCCESMST, KERINMST, KMSACMST, KONECORP, LOREFMST, LOREMST, MACYSMST, MARS, NEWAVON, ROCKWELL, NORSCMST, NSTROM, NTRCMST, PEPSIMST, PGMSTRCT, PMITNE, POSTIMST, Q2SOLMST, RECUKMST, REXELFR, SBD, SDIPLMST, FIVEBMST, SEGAMMST, SGRE, SIEMST, SMTFINAL, SYNGMAST, TMHEMST, TNTMST, TOYOTMST, TSCOMST, ULTAMST, UNILVMST, UT, WALMART, WS, XPOLOGIS,10XFTMST, MOODYCOR, TSBUK, SANOFMST, AETNA, SUNTRUST, ALCONMST, ALSTMST, AMEXGMST, AMEXMAST, AMFCMST, BRDGMST, BOFAMAST, CAREFMST, CAREMARK, CITIMAST, COMMEMST, CSGCMST, WF, CSMGCMST, CTZMAST, DEUTMST, DTCCMST, ESILRMST, FDC01MST, FIDMAST, GENPAMST, GOLDMAST, HCSCMST, HSBC0MST, IKONMAST, INGIHL, INTESMST, KROGER, LSCOMST, LULU, MASTERCD, MCKESSON, MDTRNMST, METLIFE, MMFG, MOLHMST, MOLINA, MSMAST, NNGRPMST, NOVARMST, BNYOERFP, NTRUST, NYDMVMST, ONEMNMST, ONMTMST, PFE, PRMTHMST, PTTSBMST, RBSMAST, ROCH, SCHW, INOLNMST, SWISMAST, TCGCMST, WBGMST, TIAACMST, TRPMST, UBSWMST, VOYA SERVICES COMPANY, WAMICMST, WELPOINT,ABNMST,TTTELMST,RABONMST,MARKEMST,DISHPMST,VANGUMST,MSCCAMST,PACLIMST,GHSMST,UBER

bl:
   soa: EAISSOA
   api: EAISAPI
   pvfile: d:/PhcVol.xlsx
   phcfile: d:/PHC.xlsx
   pvtfile: d:/PhcVolTarget.xlsx
   dhrtbrfile: d:/DHRTBR.xlsx

dms: Amit, Bindu, Harish, NP, Mukul


management.endpoints.web.exposure.include: "*"

#spring.profiles.active: desktop

